Repository 9oormthonUniv-seoultech/PROJECT_TEAM_WEB_FE2, pull requests merged in 2024-10, with the labels that each got.

#23 포토체크 모달 추가, 페이지 세부 기능 수정 완료
  src/assets/icons/back-icon.tsx
  src/assets/icons/close-icon.tsx
  src/assets/images/X.svg
  src/components/PhotoCheck/HashModal.tsx
  src/components/PhotoCheck/RecordModal.tsx
  src/pages/PhotoCheck/index.tsx
  src/pages/PhotoCheck/step1.tsx
  src/pages/PhotoCheck/step2.tsx
  src/pages/PhotoCheck/step3.tsx
  src/pages/PhotoReview/index.tsx
  src/pages/PhotoUpload/index.tsx
Labels: ✨ Feature

#24 사진 불러오며 진행 상황을 알려주는 애니메이션 구현, 체크 표시 구현
  src/assets/icons/progress-icon.tsx
  src/assets/images/checked.svg
  src/components/PhotoCheck/RecordModal.tsx
  src/pages/PhotoCheck/index.tsx
  src/pages/PhotoCheck/step2.tsx
  src/pages/PhotoCheck/step3.tsx
  src/pages/QRScan/index.tsx
Labels: ✨ Feature

#26 포토부스 상세페이지 UI 구현
  package-lock.json
  package.json
  src/App.tsx
  src/assets/icons/back-icon.tsx
  src/assets/icons/like-icon.tsx
  src/assets/icons/right-arrow.tsx
  src/assets/icons/star-icon.tsx
  src/assets/images/common-rate-character.svg
  src/assets/images/high-rate-character.svg
  src/assets/images/highest-rate-character.svg
  src/assets/images/img_3159.jpg
  src/assets/images/low-rate-character.svg
  src/assets/images/lowest-rate-character.svg
  src/assets/images/polygon.svg
  src/assets/images/review_tags/clean-photo.svg
  src/assets/images/review_tags/clean_booth.svg
  src/assets/images/review_tags/dark-photo.svg
  src/assets/images/review_tags/large_booth.svg
  src/assets/images/review_tags/large_wait.svg
  src/assets/images/review_tags/light-photo.svg
  src/assets/images/review_tags/multiple_bg.svg
  src/assets/images/review_tags/multiple_frame.svg
  src/assets/images/review_tags/natural.svg
  src/assets/images/review_tags/no-light.svg
  src/assets/images/review_tags/odd.svg
  src/assets/images/review_tags/powder.svg
  src/assets/images/review_tags/selfie.svg
  src/assets/images/review_tags/tool.svg
  src/components/Booth/BoothInfo.tsx
  src/components/Booth/BoothRating.tsx
  src/components/Booth/FeedImgList.tsx
  src/components/Booth/FeedTagSection.tsx
  src/components/Booth/Header.tsx
  src/components/Booth/ImgSlider.tsx
  src/components/Booth/ReviewItem.tsx
  src/components/Booth/ReviewListSection.tsx
  src/components/Common/Rating.tsx
  src/components/Home/BoothMap.tsx
  src/components/Home/BoothModal.tsx
  src/data/booth-categories.ts
  src/data/review-tag-categories.ts
  src/hooks/getImageUrl.tsx
  src/index.css
  src/pages/Booth/FeedPage.tsx
  src/pages/Booth/ImagePage.tsx
  src/pages/Booth/ReviewPage.tsx
  src/pages/Booth/index.tsx
  src/pages/PhotoReview/index.tsx
Labels: 🎨 Html&css, ✨ Feature

#31 refactor: 사진 등록 헤더부분 ui 깨짐 수정
  src/pages/PhotoCheck/step1.tsx
  src/pages/PhotoCheck/step2.tsx
  src/pages/PhotoCheck/step3.tsx
  src/pages/PhotoReview/index.tsx
  src/pages/PhotoUpload/index.tsx
  src/pages/QRScan/index.tsx
Labels: 🔨 Refactor

#32 포토부스 정보조회 API 연결 및 길찾기 기능 구현
  package-lock.json
  package.json
  src/@types/booth.ts
  src/App.tsx
  src/api/booth.ts
  src/assets/images/camera.svg
  src/assets/images/complete-review.svg
  src/components/Booth/BoothInfo.tsx
  src/components/Booth/BoothRating.tsx
  src/components/Booth/Header.tsx
  src/components/Common/Header.tsx
  src/components/Common/MapContainer.tsx
  src/components/Common/NextButton.tsx
  src/components/Common/Rating.tsx
  src/components/Home/BoothMap.tsx
  src/components/Home/BoothModal.tsx
  src/components/Home/BoothSlide.tsx
  src/components/Home/Search.tsx
  src/components/WriteReview/InputTagSection.tsx
  src/components/WriteReview/UploadImageSection.tsx
  src/data/booth-categories.ts
  src/hooks/getImageUrl.tsx
  src/hooks/getLocation.tsx
  src/main.tsx
  src/pages/Booth/index.tsx
  src/pages/CompleteScreen.tsx
  src/pages/WriteReview/index.tsx
  src/pages/WriteReview/step1.tsx
  src/pages/WriteReview/step2.tsx
  src/store/useBoothFilterStore.ts
  tailwind.config.js
Labels: 📬 API

#34 리뷰 등록 기능 구현 및 리뷰 관련 API 연결
  package-lock.json
  package.json
  src/@types/review.ts
  src/api/booth.ts
  src/api/file.ts
  src/api/index.ts
  src/api/review.ts
  src/assets/icons/right-arrow.tsx
  src/components/Booth/BoothRating.tsx
  src/components/Booth/FeedTagSection.tsx
  src/components/Booth/ImgSlider.tsx
  src/components/Booth/ReviewItem.tsx
  src/components/Booth/ReviewListSection.tsx
  src/components/Home/BoothMap.tsx
  src/components/Home/BoothModal.tsx
  src/components/WriteReview/InputTagSection.tsx
  src/components/WriteReview/UploadImageSection.tsx
  src/data/review-tag-categories.ts
  src/hooks/getImageUrl.tsx
  src/main.tsx
  src/pages/Booth/FeedPage.tsx
  src/pages/Booth/ReviewPage.tsx
  src/pages/Booth/index.tsx
  src/pages/CompleteScreen.tsx
  src/pages/Token/index.tsx
  src/pages/WriteReview/index.tsx
  src/pages/WriteReview/step1.tsx
  src/pages/WriteReview/step2.tsx
Labels: ✨ Feature, 📬 API

#38 마이페이지 UI 구현
  src/App.tsx
  src/assets/icons/edit-icon.tsx
  src/assets/icons/like-icon.tsx
  src/assets/icons/place-icon.tsx
  src/components/Common/NavBar.tsx
  src/components/My/LikeBoothCard.tsx
  src/components/My/MyReviewCard.tsx
  src/components/My/ProfileSection.tsx
  src/components/My/VisitedBoothCard.tsx
  src/pages/Home/index.tsx
  src/pages/My/FavoritesPage.tsx
  src/pages/My/LikeBoothsPage.tsx
  src/pages/My/MyReviewPage.tsx
  src/pages/My/RecordPage.tsx
  src/pages/My/VisitedBoothsPage.tsx
  src/pages/My/index.tsx
Labels: 🎨 Html&css

#39 앨범 이미지 카드 컴포넌트 구현
  src/assets/icons/like-filled-icon.tsx
  src/assets/icons/like-icon.tsx
  src/assets/icons/like-not-filled-icon.tsx
  src/assets/images/dummy-photo.jpeg
  src/components/Album/ImageCard.tsx
  src/components/Booth/BoothInfo.tsx
  src/components/My/LikeBoothCard.tsx
  src/pages/My/FavoritesPage.tsx
  src/pages/My/RecordPage.tsx
Labels: 🎨 Html&css
